theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
title: Renato Cuocolo
name: Renato Cuocolo
email: renato.cuocolo@unina.it
subtitle: Short bio, research interests/highlights, github repositories, social network and online profiles
description: Academic radiologist with an interest in radiomics and machine learning research.
url: https://rcuocolo.github.io/
author: Renato Cuocolo
