title: Renato Cuocolo
description: MD, PhD, Research Fellow at the Department of Clinical Medicine and Surgery, University of Naples "Federico II"
google_analytics: 
show_downloads: false
theme: jekyll-theme-dinky

gems:
  - jekyll-mentions
